[phases.setup]
nixPkgs = ["python311", "pip", "gcc"]

[phases.install]
cmds = ["python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "gunicorn main:app"
