[phases.setup]
nixPkgs = ["python311", "pip", "gcc"]

[phases.install]
cmds = [
  "python3 -m venv ping",
  "source ping/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn main:app"
